### ISSUE TITLE
Images for WIKI

### ISSUE THREAD

**Issue by goizueta** [AndelaOSP/guidelines#1]
![acsp_icon](https://cloud.githubusercontent.com/assets/2426597/18522700/1cb838de-7a7f-11e6-8196-aef221c4353e.png)

**Comment by andela-anandaa** [comment]
@goizueta LOL, I see the trick you did here to have to upload the image 😄

**Comment by goizueta** [comment]
![coc](https://cloud.githubusercontent.com/assets/2426597/19393110/5eca7220-9201-11e6-969a-81ea1a14b6f3.png)

**Comment by andela-anandaa** [comment]
5C's -- like it! @goizueta
