### ISSUE TITLE
UPDATE README

### ISSUE THREAD

**Issue by rowlandekemezie** [AndelaOSP/guidelines#2]
Because the README is an entrance to the entire guideline, we need to update it with: 
- [ ] Basic Introduction of the platform
- [ ] Purpose of the platform
- [ ] Brief expectation from teams 
- [ ]  A basic diagram of program flow.

These should be succinct, though. I just feel people might not head to the wiki straight if the README didn’t capture their interest.

**Comment by goizueta** [comment]
It'd be great if someone outside of Andela took a stab at this one after reading through the wiki, so we could check how their mental model aligns with ours.

**Comment by Antoh1** [comment]
Hi, I am Anthony, cohort 11 applicant, am in to take up the update challenge.

**Comment by goizueta** [comment]
Great! Go ahead and submit a Pull Request when you're done.

**Comment by awanjila** [comment]
I also would love to chip in

**Comment by goizueta** [comment]
@awanjila, that's great. You're also encouraged to either submit a PR or work off @Antoh1's when he submits his. We can always combine whatever you both submit.

**Comment by goizueta** [comment]
Closed by https://github.com/AndelaOSP/guidelines/pull/3
